import { appSchema, tableSchema } from '@nozbe/watermelondb'

export default appSchema({
  version: 4,
  tables: [
    tableSchema({
      name: 'clients',
      columns: [
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'email', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'date_of_birth', type: 'number', isOptional: true },
        { name: 'fitness_goals', type: 'string', isOptional: true },
        { name: 'medical_conditions', type: 'string', isOptional: true },
        { name: 'avatar_url', type: 'string', isOptional: true },
        { name: 'goals', type: 'string', isOptional: true },
        { name: 'health_notes', type: 'string', isOptional: true },
        { name: 'emergency_contact_name', type: 'string', isOptional: true },
        { name: 'emergency_contact_phone', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isOptional: true },
        { name: 'trainer_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'certifications', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'about_me', type: 'string', isOptional: true },
        { name: 'philosophy', type: 'string', isOptional: true },
        { name: 'methodology', type: 'string', isOptional: true },
        { name: 'branding', type: 'string', isOptional: true },
        { name: 'banner_image_path', type: 'string', isOptional: true },
        { name: 'profile_photo_path', type: 'string', isOptional: true },
        { name: 'specialties', type: 'string', isOptional: true },
        { name: 'training_types', type: 'string', isOptional: true },
        { name: 'average_rating', type: 'number', isOptional: true },
        { name: 'availability', type: 'string', isOptional: true },
        { name: 'min_service_price', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'trainer_profiles',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'username', type: 'string' },
        { name: 'certifications', type: 'string' },
        { name: 'bio', type: 'string', isOptional: true },
        { name: 'specialties', type: 'string' },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'avatar_url', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'workout_sessions',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'client_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'template_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string', isOptional: true },
        { name: 'started_at', type: 'number' },
        { name: 'finished_at', type: 'number', isOptional: true },
        { name: 'session_type', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'location_type', type: 'string', isOptional: true },
        { name: 'location_details', type: 'string', isOptional: true },
        { name: 'session_notes', type: 'string', isOptional: true },
        { name: 'client_goals', type: 'string', isOptional: true },
        { name: 'trainer_notes', type: 'string', isOptional: true },
        { name: 'session_focus', type: 'string', isOptional: true },
        { name: 'session_rating', type: 'number', isOptional: true },
        { name: 'feedback', type: 'string', isOptional: true },
        { name: 'calories_burned', type: 'number', isOptional: true },
        { name: 'steps_count', type: 'number', isOptional: true },
        { name: 'active_time_minutes', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'exercises',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'muscle_group', type: 'string', isOptional: true },
        { name: 'equipment', type: 'string', isOptional: true },
        { name: 'exercise_type', type: 'string', isOptional: true },
        { name: 'difficulty_level', type: 'string', isOptional: true },
        { name: 'equipment_needed', type: 'string', isOptional: true },
        { name: 'media_url', type: 'string', isOptional: true },
        { name: 'instructions', type: 'string', isOptional: true },
        { name: 'estimated_duration', type: 'number', isOptional: true },
        { name: 'calories_per_minute', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'workout_templates',
      columns: [
        { name: 'trainer_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'duration', type: 'number', isOptional: true },
        { name: 'difficulty_level', type: 'number', isOptional: true },
        { name: 'estimated_calories_burned', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean', isOptional: true },
        { name: 'version', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'template_exercises',
      columns: [
        { name: 'template_id', type: 'string' },
        { name: 'exercise_id', type: 'string' },
        { name: 'sets', type: 'string', isOptional: true },
        { name: 'repetitions', type: 'string', isOptional: true },
        { name: 'weight', type: 'string', isOptional: true },
        { name: 'rest_time', type: 'string', isOptional: true },
        { name: 'order', type: 'number' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'intensity_level', type: 'string', isOptional: true },
        { name: 'target_rpe', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'client_assessments',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'client_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'assessment_date', type: 'number' },
        { name: 'weight', type: 'number', isOptional: true },
        { name: 'height', type: 'number', isOptional: true },
        { name: 'body_fat_percentage', type: 'number', isOptional: true },
        { name: 'measurements', type: 'string', isOptional: true },
        { name: 'photos', type: 'string', isOptional: true },
        { name: 'assessment_type', type: 'string' },
        { name: 'assessment_method', type: 'string', isOptional: true },
        { name: 'date_performed', type: 'number' },
        { name: 'assessment_score', type: 'number', isOptional: true },
        { name: 'score_unit', type: 'string', isOptional: true },
        { name: 'body_weight', type: 'string', isOptional: true },
        { name: 'body_measurements', type: 'string', isOptional: true },
        { name: 'body_composition', type: 'string', isOptional: true },
        { name: 'fitness_level', type: 'string', isOptional: true },
        { name: 'health_conditions', type: 'string', isOptional: true },
        { name: 'injuries', type: 'string', isOptional: true },
        { name: 'medications', type: 'string', isOptional: true },
        { name: 'lifestyle_factors', type: 'string', isOptional: true },
        { name: 'goals', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'assessed_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'client_measurements',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'client_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'measured_at', type: 'number' },
        { name: 'measurement_type', type: 'string' },
        { name: 'value', type: 'number' },
        { name: 'unit', type: 'string', isOptional: true },
        { name: 'measurement_data', type: 'string', isOptional: true },
        { name: 'measurement_method', type: 'string', isOptional: true },
        { name: 'measured_by', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'client_photos',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'client_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'taken_at', type: 'number' },
        { name: 'photo_url', type: 'string' },
        { name: 'photo_type', type: 'string' },
        { name: 'caption', type: 'string', isOptional: true },
        { name: 'body_part', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'photo_notes', type: 'string', isOptional: true },
        { name: 'uploaded_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'client_exercise_logs',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'client_id', type: 'string' },
        { name: 'exercise_id', type: 'string' },
        { name: 'completed_at', type: 'number' },
        { name: 'workout_session_id', type: 'string', isOptional: true },
        { name: 'sets', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'rating', type: 'string', isOptional: true },
        { name: 'duration_minutes', type: 'number', isOptional: true },
        { name: 'calories_burned', type: 'number', isOptional: true },
        { name: 'rpe', type: 'string', isOptional: true },
        { name: 'form_quality', type: 'string', isOptional: true },
        { name: 'completed_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'trainer_services',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'service_type', type: 'string', isOptional: true },
        { name: 'duration', type: 'number' },
        { name: 'price', type: 'number' },
        { name: 'currency', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'includes', type: 'string', isOptional: true },
        { name: 'requirements', type: 'string', isOptional: true },
        { name: 'max_clients', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'trainer_packages',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'sessions_count', type: 'number' },
        { name: 'duration_weeks', type: 'number' },
        { name: 'price', type: 'number' },
        { name: 'currency', type: 'string', isOptional: true },
        { name: 'package_type', type: 'string', isOptional: true },
        { name: 'target_audience', type: 'string', isOptional: true },
        { name: 'what_included', type: 'string', isOptional: true },
        { name: 'guarantees', type: 'string', isOptional: true },
        { name: 'payment_frequency', type: 'string', isOptional: true },
        { name: 'discount_percentage', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'trainer_testimonials',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'client_name', type: 'string' },
        { name: 'content', type: 'string' },
        { name: 'testimony', type: 'string' },
        { name: 'rating', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'is_approved', type: 'boolean', isOptional: true },
        { name: 'order', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'trainer_programs',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'duration_weeks', type: 'number', isOptional: true },
        { name: 'difficulty_level', type: 'number', isOptional: true },
        { name: 'estimated_hours_per_week', type: 'number', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'price', type: 'number', isOptional: true },
        { name: 'target_audience', type: 'string', isOptional: true },
        { name: 'prerequisites', type: 'string', isOptional: true },
        { name: 'what_you_get', type: 'string', isOptional: true },
        { name: 'curriculum_overview', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'calendar_events',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'client_id', type: 'string', isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'session_type', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'start_time', type: 'number' },
        { name: 'end_time', type: 'number' },
        { name: 'event_type', type: 'string' },
        { name: 'status', type: 'string', isOptional: true },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'color', type: 'string', isOptional: true },
        { name: 'recurrence_rule', type: 'string', isOptional: true },
        { name: 'template_id', type: 'string', isOptional: true },
        { name: 'is_all_day', type: 'boolean', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'notifications',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'message', type: 'string' },
        { name: 'data', type: 'string', isOptional: true },
        { name: 'is_read', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'bookings',
      columns: [
        { name: 'user_id', type: 'string' },
        { name: 'client_id', type: 'string' },
        { name: 'trainer_id', type: 'string' },
        { name: 'session_type', type: 'string' },
        { name: 'session_date', type: 'number' },
        { name: 'session_time', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'package_id', type: 'string', isOptional: true },
        { name: 'payment_status', type: 'string', isOptional: true },
        { name: 'session_duration', type: 'number' },
        { name: 'session_cost', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'cancellation_reason', type: 'string', isOptional: true },
        { name: 'cancellation_fee', type: 'number', isOptional: true },
        { name: 'reschedule_count', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
  ],
})
