// Export all types from the types directory
// Handle export conflicts by explicitly re-exporting request types with different names
export {
  // Request types
  AuthRequest,
  LoginRequest,
  RegisterRequest,
  LogSetRequest,
  StartWorkoutSessionRequest,
  FinishWorkoutSessionRequest,
  SaveWorkoutAsTemplateRequest,
  AddSessionCommentRequest,
  StartRestTimerRequest,
  EndRestTimerRequest,
  CreateClientRequest,
  RequestClientLinkRequest,
  LogClientExerciseRequest,
  CreateProgramRequest,
  CreateTemplateRequest,
  AddExerciseToTemplateRequest,
  PlanSessionRequest,
  UpdateCalendarSessionRequest,
  DeleteCalendarSessionRequest,
  UpdateTrainerCoreInfoRequest,
  AddTrainerServiceRequest,
  UpdateTrainerServiceRequest,
  AddTrainerPackageRequest,
  UpdateTrainerPackageRequest,
  AddTrainerTestimonialRequest,
  UpdateTrainerTestimonialRequest,
  UploadTransformationPhotoRequest,
  UpdateProfileTextContentRequest,
  AddSocialLinkRequest,
  UpdateSocialLinkRequest,
  AddExternalLinkRequest,
  UpdateExternalLinkRequest,
  AddProfileBenefitRequest,
  UpdateProfileBenefitRequest,
  OrderProfileBenefitsRequest,
  UpdateProfileAvailabilityRequest,
  ProfileAvailabilityRequest,
  AddProfileExerciseRequest,
  UpdateProfileExerciseRequest,
  ConfirmBookingRequest,
  DeclineBookingRequest,
  UpdateNotificationRequest,
  HandleStripeWebhookRequest,
  GetPublicWorkoutSummaryRequest,
  FindExerciseMediaRequest,
  CreateProgramTemplateRequest,
  CopyProgramTemplateRequest,
  UpdateTemplateExercisesRequest,
  GetTemplateRestRequest,
  SendSessionReminderRequest,
  PaginationParams as RequestPaginationParams,
  SearchParams as RequestSearchParams,
  DateRange as RequestDateRange
} from './request';

// Response types
export * from './response';